#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hiddenAnaconda.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hiddenAnacondaDB")]
	public partial class ReportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertczas_odjazdu(czas_odjazdu instance);
    partial void Updateczas_odjazdu(czas_odjazdu instance);
    partial void Deleteczas_odjazdu(czas_odjazdu instance);
    partial void Insertczas_realizacji(czas_realizacji instance);
    partial void Updateczas_realizacji(czas_realizacji instance);
    partial void Deleteczas_realizacji(czas_realizacji instance);
    partial void Insertdni_kursowania(dni_kursowania instance);
    partial void Updatedni_kursowania(dni_kursowania instance);
    partial void Deletedni_kursowania(dni_kursowania instance);
    partial void Insertkierowca(kierowca instance);
    partial void Updatekierowca(kierowca instance);
    partial void Deletekierowca(kierowca instance);
    partial void Insertkur(kur instance);
    partial void Updatekur(kur instance);
    partial void Deletekur(kur instance);
    partial void Insertlinia(linia instance);
    partial void Updatelinia(linia instance);
    partial void Deletelinia(linia instance);
    partial void Insertlogowanie(logowanie instance);
    partial void Updatelogowanie(logowanie instance);
    partial void Deletelogowanie(logowanie instance);
    partial void Insertpojazd(pojazd instance);
    partial void Updatepojazd(pojazd instance);
    partial void Deletepojazd(pojazd instance);
    partial void Insertprzystanek(przystanek instance);
    partial void Updateprzystanek(przystanek instance);
    partial void Deleteprzystanek(przystanek instance);
    partial void Insertrealizacja_kursu(realizacja_kursu instance);
    partial void Updaterealizacja_kursu(realizacja_kursu instance);
    partial void Deleterealizacja_kursu(realizacja_kursu instance);
    partial void Inserttrasa(trasa instance);
    partial void Updatetrasa(trasa instance);
    partial void Deletetrasa(trasa instance);
    #endregion
		
		public ReportDataContext() : 
				base(global::hiddenAnaconda.Properties.Settings.Default.hiddenAnacondaDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<czas_odjazdu> czas_odjazdus
		{
			get
			{
				return this.GetTable<czas_odjazdu>();
			}
		}
		
		public System.Data.Linq.Table<czas_realizacji> czas_realizacjis
		{
			get
			{
				return this.GetTable<czas_realizacji>();
			}
		}
		
		public System.Data.Linq.Table<dni_kursowania> dni_kursowanias
		{
			get
			{
				return this.GetTable<dni_kursowania>();
			}
		}
		
		public System.Data.Linq.Table<kierowca> kierowcas
		{
			get
			{
				return this.GetTable<kierowca>();
			}
		}
		
		public System.Data.Linq.Table<kur> kurs
		{
			get
			{
				return this.GetTable<kur>();
			}
		}
		
		public System.Data.Linq.Table<linia> linias
		{
			get
			{
				return this.GetTable<linia>();
			}
		}
		
		public System.Data.Linq.Table<logowanie> logowanies
		{
			get
			{
				return this.GetTable<logowanie>();
			}
		}
		
		public System.Data.Linq.Table<pojazd> pojazds
		{
			get
			{
				return this.GetTable<pojazd>();
			}
		}
		
		public System.Data.Linq.Table<przystanek> przystaneks
		{
			get
			{
				return this.GetTable<przystanek>();
			}
		}
		
		public System.Data.Linq.Table<realizacja_kursu> realizacja_kursus
		{
			get
			{
				return this.GetTable<realizacja_kursu>();
			}
		}
		
		public System.Data.Linq.Table<trasa> trasas
		{
			get
			{
				return this.GetTable<trasa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.czas_odjazdu")]
	public partial class czas_odjazdu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_czasu_odjazdu;
		
		private int _id_trasy;
		
		private System.DateTime _czas_odjazdu1;
		
		private EntitySet<czas_realizacji> _czas_realizacjis;
		
		private EntitySet<kur> _kurs;
		
		private EntityRef<trasa> _trasa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_czasu_odjazduChanging(int value);
    partial void Onid_czasu_odjazduChanged();
    partial void Onid_trasyChanging(int value);
    partial void Onid_trasyChanged();
    partial void Onczas_odjazdu1Changing(System.DateTime value);
    partial void Onczas_odjazdu1Changed();
    #endregion
		
		public czas_odjazdu()
		{
			this._czas_realizacjis = new EntitySet<czas_realizacji>(new Action<czas_realizacji>(this.attach_czas_realizacjis), new Action<czas_realizacji>(this.detach_czas_realizacjis));
			this._kurs = new EntitySet<kur>(new Action<kur>(this.attach_kurs), new Action<kur>(this.detach_kurs));
			this._trasa = default(EntityRef<trasa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czasu_odjazdu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_czasu_odjazdu
		{
			get
			{
				return this._id_czasu_odjazdu;
			}
			set
			{
				if ((this._id_czasu_odjazdu != value))
				{
					this.Onid_czasu_odjazduChanging(value);
					this.SendPropertyChanging();
					this._id_czasu_odjazdu = value;
					this.SendPropertyChanged("id_czasu_odjazdu");
					this.Onid_czasu_odjazduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_trasy", DbType="Int NOT NULL")]
		public int id_trasy
		{
			get
			{
				return this._id_trasy;
			}
			set
			{
				if ((this._id_trasy != value))
				{
					if (this._trasa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_trasyChanging(value);
					this.SendPropertyChanging();
					this._id_trasy = value;
					this.SendPropertyChanged("id_trasy");
					this.Onid_trasyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="czas_odjazdu", Storage="_czas_odjazdu1", DbType="DateTime NOT NULL")]
		public System.DateTime czas_odjazdu1
		{
			get
			{
				return this._czas_odjazdu1;
			}
			set
			{
				if ((this._czas_odjazdu1 != value))
				{
					this.Onczas_odjazdu1Changing(value);
					this.SendPropertyChanging();
					this._czas_odjazdu1 = value;
					this.SendPropertyChanged("czas_odjazdu1");
					this.Onczas_odjazdu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="czas_odjazdu_czas_realizacji", Storage="_czas_realizacjis", ThisKey="id_czasu_odjazdu", OtherKey="id_czasu_odjazdu")]
		public EntitySet<czas_realizacji> czas_realizacjis
		{
			get
			{
				return this._czas_realizacjis;
			}
			set
			{
				this._czas_realizacjis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="czas_odjazdu_kur", Storage="_kurs", ThisKey="id_czasu_odjazdu", OtherKey="id_czasu_odjazdu")]
		public EntitySet<kur> kurs
		{
			get
			{
				return this._kurs;
			}
			set
			{
				this._kurs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trasa_czas_odjazdu", Storage="_trasa", ThisKey="id_trasy", OtherKey="id_trasy", IsForeignKey=true)]
		public trasa trasa
		{
			get
			{
				return this._trasa.Entity;
			}
			set
			{
				trasa previousValue = this._trasa.Entity;
				if (((previousValue != value) 
							|| (this._trasa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._trasa.Entity = null;
						previousValue.czas_odjazdus.Remove(this);
					}
					this._trasa.Entity = value;
					if ((value != null))
					{
						value.czas_odjazdus.Add(this);
						this._id_trasy = value.id_trasy;
					}
					else
					{
						this._id_trasy = default(int);
					}
					this.SendPropertyChanged("trasa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_czas_realizacjis(czas_realizacji entity)
		{
			this.SendPropertyChanging();
			entity.czas_odjazdu = this;
		}
		
		private void detach_czas_realizacjis(czas_realizacji entity)
		{
			this.SendPropertyChanging();
			entity.czas_odjazdu = null;
		}
		
		private void attach_kurs(kur entity)
		{
			this.SendPropertyChanging();
			entity.czas_odjazdu = this;
		}
		
		private void detach_kurs(kur entity)
		{
			this.SendPropertyChanging();
			entity.czas_odjazdu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.czas_realizacji")]
	public partial class czas_realizacji : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_czasu_realizacji;
		
		private System.DateTime _faktyczny_czas_odjazdu;
		
		private int _id_czasu_odjazdu;
		
		private int _id_realizacji_kursu;
		
		private EntityRef<czas_odjazdu> _czas_odjazdu;
		
		private EntityRef<realizacja_kursu> _realizacja_kursu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_czasu_realizacjiChanging(int value);
    partial void Onid_czasu_realizacjiChanged();
    partial void Onfaktyczny_czas_odjazduChanging(System.DateTime value);
    partial void Onfaktyczny_czas_odjazduChanged();
    partial void Onid_czasu_odjazduChanging(int value);
    partial void Onid_czasu_odjazduChanged();
    partial void Onid_realizacji_kursuChanging(int value);
    partial void Onid_realizacji_kursuChanged();
    #endregion
		
		public czas_realizacji()
		{
			this._czas_odjazdu = default(EntityRef<czas_odjazdu>);
			this._realizacja_kursu = default(EntityRef<realizacja_kursu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czasu_realizacji", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_czasu_realizacji
		{
			get
			{
				return this._id_czasu_realizacji;
			}
			set
			{
				if ((this._id_czasu_realizacji != value))
				{
					this.Onid_czasu_realizacjiChanging(value);
					this.SendPropertyChanging();
					this._id_czasu_realizacji = value;
					this.SendPropertyChanged("id_czasu_realizacji");
					this.Onid_czasu_realizacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faktyczny_czas_odjazdu", DbType="DateTime NOT NULL")]
		public System.DateTime faktyczny_czas_odjazdu
		{
			get
			{
				return this._faktyczny_czas_odjazdu;
			}
			set
			{
				if ((this._faktyczny_czas_odjazdu != value))
				{
					this.Onfaktyczny_czas_odjazduChanging(value);
					this.SendPropertyChanging();
					this._faktyczny_czas_odjazdu = value;
					this.SendPropertyChanged("faktyczny_czas_odjazdu");
					this.Onfaktyczny_czas_odjazduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czasu_odjazdu", DbType="Int NOT NULL")]
		public int id_czasu_odjazdu
		{
			get
			{
				return this._id_czasu_odjazdu;
			}
			set
			{
				if ((this._id_czasu_odjazdu != value))
				{
					if (this._czas_odjazdu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_czasu_odjazduChanging(value);
					this.SendPropertyChanging();
					this._id_czasu_odjazdu = value;
					this.SendPropertyChanged("id_czasu_odjazdu");
					this.Onid_czasu_odjazduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_realizacji_kursu", DbType="Int NOT NULL")]
		public int id_realizacji_kursu
		{
			get
			{
				return this._id_realizacji_kursu;
			}
			set
			{
				if ((this._id_realizacji_kursu != value))
				{
					if (this._realizacja_kursu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_realizacji_kursuChanging(value);
					this.SendPropertyChanging();
					this._id_realizacji_kursu = value;
					this.SendPropertyChanged("id_realizacji_kursu");
					this.Onid_realizacji_kursuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="czas_odjazdu_czas_realizacji", Storage="_czas_odjazdu", ThisKey="id_czasu_odjazdu", OtherKey="id_czasu_odjazdu", IsForeignKey=true)]
		public czas_odjazdu czas_odjazdu
		{
			get
			{
				return this._czas_odjazdu.Entity;
			}
			set
			{
				czas_odjazdu previousValue = this._czas_odjazdu.Entity;
				if (((previousValue != value) 
							|| (this._czas_odjazdu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._czas_odjazdu.Entity = null;
						previousValue.czas_realizacjis.Remove(this);
					}
					this._czas_odjazdu.Entity = value;
					if ((value != null))
					{
						value.czas_realizacjis.Add(this);
						this._id_czasu_odjazdu = value.id_czasu_odjazdu;
					}
					else
					{
						this._id_czasu_odjazdu = default(int);
					}
					this.SendPropertyChanged("czas_odjazdu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="realizacja_kursu_czas_realizacji", Storage="_realizacja_kursu", ThisKey="id_realizacji_kursu", OtherKey="id_realizacji_kursu", IsForeignKey=true)]
		public realizacja_kursu realizacja_kursu
		{
			get
			{
				return this._realizacja_kursu.Entity;
			}
			set
			{
				realizacja_kursu previousValue = this._realizacja_kursu.Entity;
				if (((previousValue != value) 
							|| (this._realizacja_kursu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._realizacja_kursu.Entity = null;
						previousValue.czas_realizacjis.Remove(this);
					}
					this._realizacja_kursu.Entity = value;
					if ((value != null))
					{
						value.czas_realizacjis.Add(this);
						this._id_realizacji_kursu = value.id_realizacji_kursu;
					}
					else
					{
						this._id_realizacji_kursu = default(int);
					}
					this.SendPropertyChanged("realizacja_kursu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dni_kursowania")]
	public partial class dni_kursowania : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dni_kursowania;
		
		private System.DateTime _od_dnia;
		
		private System.DateTime _do_dnia;
		
		private string _rodzaj_kursu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dni_kursowaniaChanging(int value);
    partial void Onid_dni_kursowaniaChanged();
    partial void Onod_dniaChanging(System.DateTime value);
    partial void Onod_dniaChanged();
    partial void Ondo_dniaChanging(System.DateTime value);
    partial void Ondo_dniaChanged();
    partial void Onrodzaj_kursuChanging(string value);
    partial void Onrodzaj_kursuChanged();
    #endregion
		
		public dni_kursowania()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dni_kursowania", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dni_kursowania
		{
			get
			{
				return this._id_dni_kursowania;
			}
			set
			{
				if ((this._id_dni_kursowania != value))
				{
					this.Onid_dni_kursowaniaChanging(value);
					this.SendPropertyChanging();
					this._id_dni_kursowania = value;
					this.SendPropertyChanged("id_dni_kursowania");
					this.Onid_dni_kursowaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_od_dnia", DbType="DateTime NOT NULL")]
		public System.DateTime od_dnia
		{
			get
			{
				return this._od_dnia;
			}
			set
			{
				if ((this._od_dnia != value))
				{
					this.Onod_dniaChanging(value);
					this.SendPropertyChanging();
					this._od_dnia = value;
					this.SendPropertyChanged("od_dnia");
					this.Onod_dniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_do_dnia", DbType="DateTime NOT NULL")]
		public System.DateTime do_dnia
		{
			get
			{
				return this._do_dnia;
			}
			set
			{
				if ((this._do_dnia != value))
				{
					this.Ondo_dniaChanging(value);
					this.SendPropertyChanging();
					this._do_dnia = value;
					this.SendPropertyChanged("do_dnia");
					this.Ondo_dniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rodzaj_kursu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string rodzaj_kursu
		{
			get
			{
				return this._rodzaj_kursu;
			}
			set
			{
				if ((this._rodzaj_kursu != value))
				{
					this.Onrodzaj_kursuChanging(value);
					this.SendPropertyChanging();
					this._rodzaj_kursu = value;
					this.SendPropertyChanged("rodzaj_kursu");
					this.Onrodzaj_kursuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kierowca")]
	public partial class kierowca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_kierowcy;
		
		private string _imie;
		
		private string _nazwisko;
		
		private bool _czy_pracuje;
		
		private long _PESEL;
		
		private EntitySet<realizacja_kursu> _realizacja_kursus;
		
		private EntitySet<realizacja_kursu> _realizacja_kursus1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_kierowcyChanging(int value);
    partial void Onid_kierowcyChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void Onczy_pracujeChanging(bool value);
    partial void Onczy_pracujeChanged();
    partial void OnPESELChanging(long value);
    partial void OnPESELChanged();
    #endregion
		
		public kierowca()
		{
			this._realizacja_kursus = new EntitySet<realizacja_kursu>(new Action<realizacja_kursu>(this.attach_realizacja_kursus), new Action<realizacja_kursu>(this.detach_realizacja_kursus));
			this._realizacja_kursus1 = new EntitySet<realizacja_kursu>(new Action<realizacja_kursu>(this.attach_realizacja_kursus1), new Action<realizacja_kursu>(this.detach_realizacja_kursus1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kierowcy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_kierowcy
		{
			get
			{
				return this._id_kierowcy;
			}
			set
			{
				if ((this._id_kierowcy != value))
				{
					this.Onid_kierowcyChanging(value);
					this.SendPropertyChanging();
					this._id_kierowcy = value;
					this.SendPropertyChanged("id_kierowcy");
					this.Onid_kierowcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czy_pracuje", DbType="Bit NOT NULL")]
		public bool czy_pracuje
		{
			get
			{
				return this._czy_pracuje;
			}
			set
			{
				if ((this._czy_pracuje != value))
				{
					this.Onczy_pracujeChanging(value);
					this.SendPropertyChanging();
					this._czy_pracuje = value;
					this.SendPropertyChanged("czy_pracuje");
					this.Onczy_pracujeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PESEL", DbType="BigInt NOT NULL")]
		public long PESEL
		{
			get
			{
				return this._PESEL;
			}
			set
			{
				if ((this._PESEL != value))
				{
					this.OnPESELChanging(value);
					this.SendPropertyChanging();
					this._PESEL = value;
					this.SendPropertyChanged("PESEL");
					this.OnPESELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kierowca_realizacja_kursu", Storage="_realizacja_kursus", ThisKey="id_kierowcy", OtherKey="id_przypisanego_kierowcy")]
		public EntitySet<realizacja_kursu> realizacja_kursus
		{
			get
			{
				return this._realizacja_kursus;
			}
			set
			{
				this._realizacja_kursus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kierowca_realizacja_kursu1", Storage="_realizacja_kursus1", ThisKey="id_kierowcy", OtherKey="id_wykonujacego_kierowcy")]
		public EntitySet<realizacja_kursu> realizacja_kursus1
		{
			get
			{
				return this._realizacja_kursus1;
			}
			set
			{
				this._realizacja_kursus1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_realizacja_kursus(realizacja_kursu entity)
		{
			this.SendPropertyChanging();
			entity.kierowca = this;
		}
		
		private void detach_realizacja_kursus(realizacja_kursu entity)
		{
			this.SendPropertyChanging();
			entity.kierowca = null;
		}
		
		private void attach_realizacja_kursus1(realizacja_kursu entity)
		{
			this.SendPropertyChanging();
			entity.kierowca1 = this;
		}
		
		private void detach_realizacja_kursus1(realizacja_kursu entity)
		{
			this.SendPropertyChanging();
			entity.kierowca1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kurs")]
	public partial class kur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_kursu;
		
		private int _id_linii;
		
		private int _id_czasu_odjazdu;
		
		private int _id_trasy;
		
		private int _ktory_kurs_danego_dnia;
		
		private string _rodzaj_kursu;
		
		private EntitySet<realizacja_kursu> _realizacja_kursus;
		
		private EntityRef<czas_odjazdu> _czas_odjazdu;
		
		private EntityRef<linia> _linia;
		
		private EntityRef<trasa> _trasa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_kursuChanging(int value);
    partial void Onid_kursuChanged();
    partial void Onid_liniiChanging(int value);
    partial void Onid_liniiChanged();
    partial void Onid_czasu_odjazduChanging(int value);
    partial void Onid_czasu_odjazduChanged();
    partial void Onid_trasyChanging(int value);
    partial void Onid_trasyChanged();
    partial void Onktory_kurs_danego_dniaChanging(int value);
    partial void Onktory_kurs_danego_dniaChanged();
    partial void Onrodzaj_kursuChanging(string value);
    partial void Onrodzaj_kursuChanged();
    #endregion
		
		public kur()
		{
			this._realizacja_kursus = new EntitySet<realizacja_kursu>(new Action<realizacja_kursu>(this.attach_realizacja_kursus), new Action<realizacja_kursu>(this.detach_realizacja_kursus));
			this._czas_odjazdu = default(EntityRef<czas_odjazdu>);
			this._linia = default(EntityRef<linia>);
			this._trasa = default(EntityRef<trasa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kursu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_kursu
		{
			get
			{
				return this._id_kursu;
			}
			set
			{
				if ((this._id_kursu != value))
				{
					this.Onid_kursuChanging(value);
					this.SendPropertyChanging();
					this._id_kursu = value;
					this.SendPropertyChanged("id_kursu");
					this.Onid_kursuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_linii", DbType="Int NOT NULL")]
		public int id_linii
		{
			get
			{
				return this._id_linii;
			}
			set
			{
				if ((this._id_linii != value))
				{
					if (this._linia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_liniiChanging(value);
					this.SendPropertyChanging();
					this._id_linii = value;
					this.SendPropertyChanged("id_linii");
					this.Onid_liniiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_czasu_odjazdu", DbType="Int NOT NULL")]
		public int id_czasu_odjazdu
		{
			get
			{
				return this._id_czasu_odjazdu;
			}
			set
			{
				if ((this._id_czasu_odjazdu != value))
				{
					if (this._czas_odjazdu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_czasu_odjazduChanging(value);
					this.SendPropertyChanging();
					this._id_czasu_odjazdu = value;
					this.SendPropertyChanged("id_czasu_odjazdu");
					this.Onid_czasu_odjazduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_trasy", DbType="Int NOT NULL")]
		public int id_trasy
		{
			get
			{
				return this._id_trasy;
			}
			set
			{
				if ((this._id_trasy != value))
				{
					if (this._trasa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_trasyChanging(value);
					this.SendPropertyChanging();
					this._id_trasy = value;
					this.SendPropertyChanged("id_trasy");
					this.Onid_trasyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ktory_kurs_danego_dnia", DbType="Int NOT NULL")]
		public int ktory_kurs_danego_dnia
		{
			get
			{
				return this._ktory_kurs_danego_dnia;
			}
			set
			{
				if ((this._ktory_kurs_danego_dnia != value))
				{
					this.Onktory_kurs_danego_dniaChanging(value);
					this.SendPropertyChanging();
					this._ktory_kurs_danego_dnia = value;
					this.SendPropertyChanged("ktory_kurs_danego_dnia");
					this.Onktory_kurs_danego_dniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rodzaj_kursu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string rodzaj_kursu
		{
			get
			{
				return this._rodzaj_kursu;
			}
			set
			{
				if ((this._rodzaj_kursu != value))
				{
					this.Onrodzaj_kursuChanging(value);
					this.SendPropertyChanging();
					this._rodzaj_kursu = value;
					this.SendPropertyChanged("rodzaj_kursu");
					this.Onrodzaj_kursuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kur_realizacja_kursu", Storage="_realizacja_kursus", ThisKey="id_kursu", OtherKey="id_kursu")]
		public EntitySet<realizacja_kursu> realizacja_kursus
		{
			get
			{
				return this._realizacja_kursus;
			}
			set
			{
				this._realizacja_kursus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="czas_odjazdu_kur", Storage="_czas_odjazdu", ThisKey="id_czasu_odjazdu", OtherKey="id_czasu_odjazdu", IsForeignKey=true)]
		public czas_odjazdu czas_odjazdu
		{
			get
			{
				return this._czas_odjazdu.Entity;
			}
			set
			{
				czas_odjazdu previousValue = this._czas_odjazdu.Entity;
				if (((previousValue != value) 
							|| (this._czas_odjazdu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._czas_odjazdu.Entity = null;
						previousValue.kurs.Remove(this);
					}
					this._czas_odjazdu.Entity = value;
					if ((value != null))
					{
						value.kurs.Add(this);
						this._id_czasu_odjazdu = value.id_czasu_odjazdu;
					}
					else
					{
						this._id_czasu_odjazdu = default(int);
					}
					this.SendPropertyChanged("czas_odjazdu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="linia_kur", Storage="_linia", ThisKey="id_linii", OtherKey="id_linii", IsForeignKey=true)]
		public linia linia
		{
			get
			{
				return this._linia.Entity;
			}
			set
			{
				linia previousValue = this._linia.Entity;
				if (((previousValue != value) 
							|| (this._linia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._linia.Entity = null;
						previousValue.kurs.Remove(this);
					}
					this._linia.Entity = value;
					if ((value != null))
					{
						value.kurs.Add(this);
						this._id_linii = value.id_linii;
					}
					else
					{
						this._id_linii = default(int);
					}
					this.SendPropertyChanged("linia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trasa_kur", Storage="_trasa", ThisKey="id_trasy", OtherKey="id_trasy", IsForeignKey=true)]
		public trasa trasa
		{
			get
			{
				return this._trasa.Entity;
			}
			set
			{
				trasa previousValue = this._trasa.Entity;
				if (((previousValue != value) 
							|| (this._trasa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._trasa.Entity = null;
						previousValue.kurs.Remove(this);
					}
					this._trasa.Entity = value;
					if ((value != null))
					{
						value.kurs.Add(this);
						this._id_trasy = value.id_trasy;
					}
					else
					{
						this._id_trasy = default(int);
					}
					this.SendPropertyChanged("trasa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_realizacja_kursus(realizacja_kursu entity)
		{
			this.SendPropertyChanging();
			entity.kur = this;
		}
		
		private void detach_realizacja_kursus(realizacja_kursu entity)
		{
			this.SendPropertyChanging();
			entity.kur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.linia")]
	public partial class linia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_linii;
		
		private bool _czy_zapetla;
		
		private EntitySet<kur> _kurs;
		
		private EntitySet<trasa> _trasas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_liniiChanging(int value);
    partial void Onid_liniiChanged();
    partial void Onczy_zapetlaChanging(bool value);
    partial void Onczy_zapetlaChanged();
    #endregion
		
		public linia()
		{
			this._kurs = new EntitySet<kur>(new Action<kur>(this.attach_kurs), new Action<kur>(this.detach_kurs));
			this._trasas = new EntitySet<trasa>(new Action<trasa>(this.attach_trasas), new Action<trasa>(this.detach_trasas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_linii", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_linii
		{
			get
			{
				return this._id_linii;
			}
			set
			{
				if ((this._id_linii != value))
				{
					this.Onid_liniiChanging(value);
					this.SendPropertyChanging();
					this._id_linii = value;
					this.SendPropertyChanged("id_linii");
					this.Onid_liniiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czy_zapetla", DbType="Bit NOT NULL")]
		public bool czy_zapetla
		{
			get
			{
				return this._czy_zapetla;
			}
			set
			{
				if ((this._czy_zapetla != value))
				{
					this.Onczy_zapetlaChanging(value);
					this.SendPropertyChanging();
					this._czy_zapetla = value;
					this.SendPropertyChanged("czy_zapetla");
					this.Onczy_zapetlaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="linia_kur", Storage="_kurs", ThisKey="id_linii", OtherKey="id_linii")]
		public EntitySet<kur> kurs
		{
			get
			{
				return this._kurs;
			}
			set
			{
				this._kurs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="linia_trasa", Storage="_trasas", ThisKey="id_linii", OtherKey="id_linii")]
		public EntitySet<trasa> trasas
		{
			get
			{
				return this._trasas;
			}
			set
			{
				this._trasas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kurs(kur entity)
		{
			this.SendPropertyChanging();
			entity.linia = this;
		}
		
		private void detach_kurs(kur entity)
		{
			this.SendPropertyChanging();
			entity.linia = null;
		}
		
		private void attach_trasas(trasa entity)
		{
			this.SendPropertyChanging();
			entity.linia = this;
		}
		
		private void detach_trasas(trasa entity)
		{
			this.SendPropertyChanging();
			entity.linia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.logowanie")]
	public partial class logowanie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_uzytkownika;
		
		private string _login;
		
		private string _hasz;
		
		private int _poziom_uprawnien;
		
		private bool _czy_aktywny;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_uzytkownikaChanging(int value);
    partial void Onid_uzytkownikaChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnhaszChanging(string value);
    partial void OnhaszChanged();
    partial void Onpoziom_uprawnienChanging(int value);
    partial void Onpoziom_uprawnienChanged();
    partial void Onczy_aktywnyChanging(bool value);
    partial void Onczy_aktywnyChanged();
    #endregion
		
		public logowanie()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_uzytkownika", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_uzytkownika
		{
			get
			{
				return this._id_uzytkownika;
			}
			set
			{
				if ((this._id_uzytkownika != value))
				{
					this.Onid_uzytkownikaChanging(value);
					this.SendPropertyChanging();
					this._id_uzytkownika = value;
					this.SendPropertyChanged("id_uzytkownika");
					this.Onid_uzytkownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasz", DbType="NVarChar(72) NOT NULL", CanBeNull=false)]
		public string hasz
		{
			get
			{
				return this._hasz;
			}
			set
			{
				if ((this._hasz != value))
				{
					this.OnhaszChanging(value);
					this.SendPropertyChanging();
					this._hasz = value;
					this.SendPropertyChanged("hasz");
					this.OnhaszChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poziom_uprawnien", DbType="Int NOT NULL")]
		public int poziom_uprawnien
		{
			get
			{
				return this._poziom_uprawnien;
			}
			set
			{
				if ((this._poziom_uprawnien != value))
				{
					this.Onpoziom_uprawnienChanging(value);
					this.SendPropertyChanging();
					this._poziom_uprawnien = value;
					this.SendPropertyChanged("poziom_uprawnien");
					this.Onpoziom_uprawnienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czy_aktywny", DbType="Bit NOT NULL")]
		public bool czy_aktywny
		{
			get
			{
				return this._czy_aktywny;
			}
			set
			{
				if ((this._czy_aktywny != value))
				{
					this.Onczy_aktywnyChanging(value);
					this.SendPropertyChanging();
					this._czy_aktywny = value;
					this.SendPropertyChanged("czy_aktywny");
					this.Onczy_aktywnyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pojazd")]
	public partial class pojazd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pojazdu;
		
		private string _nr_rejestracyjny;
		
		private string _nr_VIN;
		
		private string _model;
		
		private string _marka;
		
		private System.DateTime _data_produkcji;
		
		private bool _czy_niskopodlogowy;
		
		private bool _czy_sprawny;
		
		private EntitySet<realizacja_kursu> _realizacja_kursus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pojazduChanging(int value);
    partial void Onid_pojazduChanged();
    partial void Onnr_rejestracyjnyChanging(string value);
    partial void Onnr_rejestracyjnyChanged();
    partial void Onnr_VINChanging(string value);
    partial void Onnr_VINChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnmarkaChanging(string value);
    partial void OnmarkaChanged();
    partial void Ondata_produkcjiChanging(System.DateTime value);
    partial void Ondata_produkcjiChanged();
    partial void Onczy_niskopodlogowyChanging(bool value);
    partial void Onczy_niskopodlogowyChanged();
    partial void Onczy_sprawnyChanging(bool value);
    partial void Onczy_sprawnyChanged();
    #endregion
		
		public pojazd()
		{
			this._realizacja_kursus = new EntitySet<realizacja_kursu>(new Action<realizacja_kursu>(this.attach_realizacja_kursus), new Action<realizacja_kursu>(this.detach_realizacja_kursus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pojazdu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pojazdu
		{
			get
			{
				return this._id_pojazdu;
			}
			set
			{
				if ((this._id_pojazdu != value))
				{
					this.Onid_pojazduChanging(value);
					this.SendPropertyChanging();
					this._id_pojazdu = value;
					this.SendPropertyChanged("id_pojazdu");
					this.Onid_pojazduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_rejestracyjny", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string nr_rejestracyjny
		{
			get
			{
				return this._nr_rejestracyjny;
			}
			set
			{
				if ((this._nr_rejestracyjny != value))
				{
					this.Onnr_rejestracyjnyChanging(value);
					this.SendPropertyChanging();
					this._nr_rejestracyjny = value;
					this.SendPropertyChanged("nr_rejestracyjny");
					this.Onnr_rejestracyjnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_VIN", DbType="NVarChar(17) NOT NULL", CanBeNull=false)]
		public string nr_VIN
		{
			get
			{
				return this._nr_VIN;
			}
			set
			{
				if ((this._nr_VIN != value))
				{
					this.Onnr_VINChanging(value);
					this.SendPropertyChanging();
					this._nr_VIN = value;
					this.SendPropertyChanged("nr_VIN");
					this.Onnr_VINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marka", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string marka
		{
			get
			{
				return this._marka;
			}
			set
			{
				if ((this._marka != value))
				{
					this.OnmarkaChanging(value);
					this.SendPropertyChanging();
					this._marka = value;
					this.SendPropertyChanged("marka");
					this.OnmarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_produkcji", DbType="DateTime NOT NULL")]
		public System.DateTime data_produkcji
		{
			get
			{
				return this._data_produkcji;
			}
			set
			{
				if ((this._data_produkcji != value))
				{
					this.Ondata_produkcjiChanging(value);
					this.SendPropertyChanging();
					this._data_produkcji = value;
					this.SendPropertyChanged("data_produkcji");
					this.Ondata_produkcjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czy_niskopodlogowy", DbType="Bit NOT NULL")]
		public bool czy_niskopodlogowy
		{
			get
			{
				return this._czy_niskopodlogowy;
			}
			set
			{
				if ((this._czy_niskopodlogowy != value))
				{
					this.Onczy_niskopodlogowyChanging(value);
					this.SendPropertyChanging();
					this._czy_niskopodlogowy = value;
					this.SendPropertyChanged("czy_niskopodlogowy");
					this.Onczy_niskopodlogowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czy_sprawny", DbType="Bit NOT NULL")]
		public bool czy_sprawny
		{
			get
			{
				return this._czy_sprawny;
			}
			set
			{
				if ((this._czy_sprawny != value))
				{
					this.Onczy_sprawnyChanging(value);
					this.SendPropertyChanging();
					this._czy_sprawny = value;
					this.SendPropertyChanged("czy_sprawny");
					this.Onczy_sprawnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pojazd_realizacja_kursu", Storage="_realizacja_kursus", ThisKey="id_pojazdu", OtherKey="id_pojazdu")]
		public EntitySet<realizacja_kursu> realizacja_kursus
		{
			get
			{
				return this._realizacja_kursus;
			}
			set
			{
				this._realizacja_kursus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_realizacja_kursus(realizacja_kursu entity)
		{
			this.SendPropertyChanging();
			entity.pojazd = this;
		}
		
		private void detach_realizacja_kursus(realizacja_kursu entity)
		{
			this.SendPropertyChanging();
			entity.pojazd = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.przystanek")]
	public partial class przystanek : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_przystanku;
		
		private string _nazwa;
		
		private string _miasto;
		
		private string _kierunek;
		
		private EntitySet<trasa> _trasas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_przystankuChanging(int value);
    partial void Onid_przystankuChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void OnmiastoChanging(string value);
    partial void OnmiastoChanged();
    partial void OnkierunekChanging(string value);
    partial void OnkierunekChanged();
    #endregion
		
		public przystanek()
		{
			this._trasas = new EntitySet<trasa>(new Action<trasa>(this.attach_trasas), new Action<trasa>(this.detach_trasas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_przystanku", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_przystanku
		{
			get
			{
				return this._id_przystanku;
			}
			set
			{
				if ((this._id_przystanku != value))
				{
					this.Onid_przystankuChanging(value);
					this.SendPropertyChanging();
					this._id_przystanku = value;
					this.SendPropertyChanged("id_przystanku");
					this.Onid_przystankuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miasto", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string miasto
		{
			get
			{
				return this._miasto;
			}
			set
			{
				if ((this._miasto != value))
				{
					this.OnmiastoChanging(value);
					this.SendPropertyChanging();
					this._miasto = value;
					this.SendPropertyChanged("miasto");
					this.OnmiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kierunek", DbType="NVarChar(60)")]
		public string kierunek
		{
			get
			{
				return this._kierunek;
			}
			set
			{
				if ((this._kierunek != value))
				{
					this.OnkierunekChanging(value);
					this.SendPropertyChanging();
					this._kierunek = value;
					this.SendPropertyChanged("kierunek");
					this.OnkierunekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="przystanek_trasa", Storage="_trasas", ThisKey="id_przystanku", OtherKey="id_przystanku")]
		public EntitySet<trasa> trasas
		{
			get
			{
				return this._trasas;
			}
			set
			{
				this._trasas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_trasas(trasa entity)
		{
			this.SendPropertyChanging();
			entity.przystanek = this;
		}
		
		private void detach_trasas(trasa entity)
		{
			this.SendPropertyChanging();
			entity.przystanek = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.realizacja_kursu")]
	public partial class realizacja_kursu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_realizacji_kursu;
		
		private int _id_przypisanego_kierowcy;
		
		private System.Nullable<int> _id_wykonujacego_kierowcy;
		
		private int _id_pojazdu;
		
		private int _id_kursu;
		
		private System.DateTime _data_realizacji;
		
		private EntitySet<czas_realizacji> _czas_realizacjis;
		
		private EntityRef<kur> _kur;
		
		private EntityRef<kierowca> _kierowca;
		
		private EntityRef<pojazd> _pojazd;
		
		private EntityRef<kierowca> _kierowca1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_realizacji_kursuChanging(int value);
    partial void Onid_realizacji_kursuChanged();
    partial void Onid_przypisanego_kierowcyChanging(int value);
    partial void Onid_przypisanego_kierowcyChanged();
    partial void Onid_wykonujacego_kierowcyChanging(System.Nullable<int> value);
    partial void Onid_wykonujacego_kierowcyChanged();
    partial void Onid_pojazduChanging(int value);
    partial void Onid_pojazduChanged();
    partial void Onid_kursuChanging(int value);
    partial void Onid_kursuChanged();
    partial void Ondata_realizacjiChanging(System.DateTime value);
    partial void Ondata_realizacjiChanged();
    #endregion
		
		public realizacja_kursu()
		{
			this._czas_realizacjis = new EntitySet<czas_realizacji>(new Action<czas_realizacji>(this.attach_czas_realizacjis), new Action<czas_realizacji>(this.detach_czas_realizacjis));
			this._kur = default(EntityRef<kur>);
			this._kierowca = default(EntityRef<kierowca>);
			this._pojazd = default(EntityRef<pojazd>);
			this._kierowca1 = default(EntityRef<kierowca>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_realizacji_kursu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_realizacji_kursu
		{
			get
			{
				return this._id_realizacji_kursu;
			}
			set
			{
				if ((this._id_realizacji_kursu != value))
				{
					this.Onid_realizacji_kursuChanging(value);
					this.SendPropertyChanging();
					this._id_realizacji_kursu = value;
					this.SendPropertyChanged("id_realizacji_kursu");
					this.Onid_realizacji_kursuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_przypisanego_kierowcy", DbType="Int NOT NULL")]
		public int id_przypisanego_kierowcy
		{
			get
			{
				return this._id_przypisanego_kierowcy;
			}
			set
			{
				if ((this._id_przypisanego_kierowcy != value))
				{
					if (this._kierowca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_przypisanego_kierowcyChanging(value);
					this.SendPropertyChanging();
					this._id_przypisanego_kierowcy = value;
					this.SendPropertyChanged("id_przypisanego_kierowcy");
					this.Onid_przypisanego_kierowcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_wykonujacego_kierowcy", DbType="Int")]
		public System.Nullable<int> id_wykonujacego_kierowcy
		{
			get
			{
				return this._id_wykonujacego_kierowcy;
			}
			set
			{
				if ((this._id_wykonujacego_kierowcy != value))
				{
					if (this._kierowca1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_wykonujacego_kierowcyChanging(value);
					this.SendPropertyChanging();
					this._id_wykonujacego_kierowcy = value;
					this.SendPropertyChanged("id_wykonujacego_kierowcy");
					this.Onid_wykonujacego_kierowcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pojazdu", DbType="Int NOT NULL")]
		public int id_pojazdu
		{
			get
			{
				return this._id_pojazdu;
			}
			set
			{
				if ((this._id_pojazdu != value))
				{
					if (this._pojazd.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pojazduChanging(value);
					this.SendPropertyChanging();
					this._id_pojazdu = value;
					this.SendPropertyChanged("id_pojazdu");
					this.Onid_pojazduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kursu", DbType="Int NOT NULL")]
		public int id_kursu
		{
			get
			{
				return this._id_kursu;
			}
			set
			{
				if ((this._id_kursu != value))
				{
					if (this._kur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_kursuChanging(value);
					this.SendPropertyChanging();
					this._id_kursu = value;
					this.SendPropertyChanged("id_kursu");
					this.Onid_kursuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_realizacji", DbType="DateTime NOT NULL")]
		public System.DateTime data_realizacji
		{
			get
			{
				return this._data_realizacji;
			}
			set
			{
				if ((this._data_realizacji != value))
				{
					this.Ondata_realizacjiChanging(value);
					this.SendPropertyChanging();
					this._data_realizacji = value;
					this.SendPropertyChanged("data_realizacji");
					this.Ondata_realizacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="realizacja_kursu_czas_realizacji", Storage="_czas_realizacjis", ThisKey="id_realizacji_kursu", OtherKey="id_realizacji_kursu")]
		public EntitySet<czas_realizacji> czas_realizacjis
		{
			get
			{
				return this._czas_realizacjis;
			}
			set
			{
				this._czas_realizacjis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kur_realizacja_kursu", Storage="_kur", ThisKey="id_kursu", OtherKey="id_kursu", IsForeignKey=true)]
		public kur kur
		{
			get
			{
				return this._kur.Entity;
			}
			set
			{
				kur previousValue = this._kur.Entity;
				if (((previousValue != value) 
							|| (this._kur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kur.Entity = null;
						previousValue.realizacja_kursus.Remove(this);
					}
					this._kur.Entity = value;
					if ((value != null))
					{
						value.realizacja_kursus.Add(this);
						this._id_kursu = value.id_kursu;
					}
					else
					{
						this._id_kursu = default(int);
					}
					this.SendPropertyChanged("kur");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kierowca_realizacja_kursu", Storage="_kierowca", ThisKey="id_przypisanego_kierowcy", OtherKey="id_kierowcy", IsForeignKey=true)]
		public kierowca kierowca
		{
			get
			{
				return this._kierowca.Entity;
			}
			set
			{
				kierowca previousValue = this._kierowca.Entity;
				if (((previousValue != value) 
							|| (this._kierowca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kierowca.Entity = null;
						previousValue.realizacja_kursus.Remove(this);
					}
					this._kierowca.Entity = value;
					if ((value != null))
					{
						value.realizacja_kursus.Add(this);
						this._id_przypisanego_kierowcy = value.id_kierowcy;
					}
					else
					{
						this._id_przypisanego_kierowcy = default(int);
					}
					this.SendPropertyChanged("kierowca");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pojazd_realizacja_kursu", Storage="_pojazd", ThisKey="id_pojazdu", OtherKey="id_pojazdu", IsForeignKey=true)]
		public pojazd pojazd
		{
			get
			{
				return this._pojazd.Entity;
			}
			set
			{
				pojazd previousValue = this._pojazd.Entity;
				if (((previousValue != value) 
							|| (this._pojazd.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pojazd.Entity = null;
						previousValue.realizacja_kursus.Remove(this);
					}
					this._pojazd.Entity = value;
					if ((value != null))
					{
						value.realizacja_kursus.Add(this);
						this._id_pojazdu = value.id_pojazdu;
					}
					else
					{
						this._id_pojazdu = default(int);
					}
					this.SendPropertyChanged("pojazd");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kierowca_realizacja_kursu1", Storage="_kierowca1", ThisKey="id_wykonujacego_kierowcy", OtherKey="id_kierowcy", IsForeignKey=true)]
		public kierowca kierowca1
		{
			get
			{
				return this._kierowca1.Entity;
			}
			set
			{
				kierowca previousValue = this._kierowca1.Entity;
				if (((previousValue != value) 
							|| (this._kierowca1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kierowca1.Entity = null;
						previousValue.realizacja_kursus1.Remove(this);
					}
					this._kierowca1.Entity = value;
					if ((value != null))
					{
						value.realizacja_kursus1.Add(this);
						this._id_wykonujacego_kierowcy = value.id_kierowcy;
					}
					else
					{
						this._id_wykonujacego_kierowcy = default(Nullable<int>);
					}
					this.SendPropertyChanged("kierowca1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_czas_realizacjis(czas_realizacji entity)
		{
			this.SendPropertyChanging();
			entity.realizacja_kursu = this;
		}
		
		private void detach_czas_realizacjis(czas_realizacji entity)
		{
			this.SendPropertyChanging();
			entity.realizacja_kursu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trasa")]
	public partial class trasa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_trasy;
		
		private int _id_linii;
		
		private int _id_przystanku;
		
		private int _kolejnosc_przystankow;
		
		private int _nr_trasy;
		
		private EntitySet<czas_odjazdu> _czas_odjazdus;
		
		private EntitySet<kur> _kurs;
		
		private EntityRef<przystanek> _przystanek;
		
		private EntityRef<linia> _linia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_trasyChanging(int value);
    partial void Onid_trasyChanged();
    partial void Onid_liniiChanging(int value);
    partial void Onid_liniiChanged();
    partial void Onid_przystankuChanging(int value);
    partial void Onid_przystankuChanged();
    partial void Onkolejnosc_przystankowChanging(int value);
    partial void Onkolejnosc_przystankowChanged();
    partial void Onnr_trasyChanging(int value);
    partial void Onnr_trasyChanged();
    #endregion
		
		public trasa()
		{
			this._czas_odjazdus = new EntitySet<czas_odjazdu>(new Action<czas_odjazdu>(this.attach_czas_odjazdus), new Action<czas_odjazdu>(this.detach_czas_odjazdus));
			this._kurs = new EntitySet<kur>(new Action<kur>(this.attach_kurs), new Action<kur>(this.detach_kurs));
			this._przystanek = default(EntityRef<przystanek>);
			this._linia = default(EntityRef<linia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_trasy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_trasy
		{
			get
			{
				return this._id_trasy;
			}
			set
			{
				if ((this._id_trasy != value))
				{
					this.Onid_trasyChanging(value);
					this.SendPropertyChanging();
					this._id_trasy = value;
					this.SendPropertyChanged("id_trasy");
					this.Onid_trasyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_linii", DbType="Int NOT NULL")]
		public int id_linii
		{
			get
			{
				return this._id_linii;
			}
			set
			{
				if ((this._id_linii != value))
				{
					if (this._linia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_liniiChanging(value);
					this.SendPropertyChanging();
					this._id_linii = value;
					this.SendPropertyChanged("id_linii");
					this.Onid_liniiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_przystanku", DbType="Int NOT NULL")]
		public int id_przystanku
		{
			get
			{
				return this._id_przystanku;
			}
			set
			{
				if ((this._id_przystanku != value))
				{
					if (this._przystanek.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_przystankuChanging(value);
					this.SendPropertyChanging();
					this._id_przystanku = value;
					this.SendPropertyChanged("id_przystanku");
					this.Onid_przystankuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kolejnosc_przystankow", DbType="Int NOT NULL")]
		public int kolejnosc_przystankow
		{
			get
			{
				return this._kolejnosc_przystankow;
			}
			set
			{
				if ((this._kolejnosc_przystankow != value))
				{
					this.Onkolejnosc_przystankowChanging(value);
					this.SendPropertyChanging();
					this._kolejnosc_przystankow = value;
					this.SendPropertyChanged("kolejnosc_przystankow");
					this.Onkolejnosc_przystankowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_trasy", DbType="Int NOT NULL")]
		public int nr_trasy
		{
			get
			{
				return this._nr_trasy;
			}
			set
			{
				if ((this._nr_trasy != value))
				{
					this.Onnr_trasyChanging(value);
					this.SendPropertyChanging();
					this._nr_trasy = value;
					this.SendPropertyChanged("nr_trasy");
					this.Onnr_trasyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trasa_czas_odjazdu", Storage="_czas_odjazdus", ThisKey="id_trasy", OtherKey="id_trasy")]
		public EntitySet<czas_odjazdu> czas_odjazdus
		{
			get
			{
				return this._czas_odjazdus;
			}
			set
			{
				this._czas_odjazdus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trasa_kur", Storage="_kurs", ThisKey="id_trasy", OtherKey="id_trasy")]
		public EntitySet<kur> kurs
		{
			get
			{
				return this._kurs;
			}
			set
			{
				this._kurs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="przystanek_trasa", Storage="_przystanek", ThisKey="id_przystanku", OtherKey="id_przystanku", IsForeignKey=true)]
		public przystanek przystanek
		{
			get
			{
				return this._przystanek.Entity;
			}
			set
			{
				przystanek previousValue = this._przystanek.Entity;
				if (((previousValue != value) 
							|| (this._przystanek.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._przystanek.Entity = null;
						previousValue.trasas.Remove(this);
					}
					this._przystanek.Entity = value;
					if ((value != null))
					{
						value.trasas.Add(this);
						this._id_przystanku = value.id_przystanku;
					}
					else
					{
						this._id_przystanku = default(int);
					}
					this.SendPropertyChanged("przystanek");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="linia_trasa", Storage="_linia", ThisKey="id_linii", OtherKey="id_linii", IsForeignKey=true)]
		public linia linia
		{
			get
			{
				return this._linia.Entity;
			}
			set
			{
				linia previousValue = this._linia.Entity;
				if (((previousValue != value) 
							|| (this._linia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._linia.Entity = null;
						previousValue.trasas.Remove(this);
					}
					this._linia.Entity = value;
					if ((value != null))
					{
						value.trasas.Add(this);
						this._id_linii = value.id_linii;
					}
					else
					{
						this._id_linii = default(int);
					}
					this.SendPropertyChanged("linia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_czas_odjazdus(czas_odjazdu entity)
		{
			this.SendPropertyChanging();
			entity.trasa = this;
		}
		
		private void detach_czas_odjazdus(czas_odjazdu entity)
		{
			this.SendPropertyChanging();
			entity.trasa = null;
		}
		
		private void attach_kurs(kur entity)
		{
			this.SendPropertyChanging();
			entity.trasa = this;
		}
		
		private void detach_kurs(kur entity)
		{
			this.SendPropertyChanging();
			entity.trasa = null;
		}
	}
}
#pragma warning restore 1591
